"""empty message

Revision ID: 6aabe92e79bf
Revises: e8868c8bc51e
Create Date: 2021-08-27 22:16:13.070431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aabe92e79bf'
down_revision = 'e8868c8bc51e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('add_stock', sa.Column('isbn', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'add_stock', type_='foreignkey')
    op.create_foreign_key(None, 'add_stock', 'book', ['isbn'], ['isbn'], ondelete='CASCADE')
    op.drop_column('add_stock', 'book_name')
    op.alter_column('comment', 'modified_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'modified_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.add_column('add_stock', sa.Column('book_name', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'add_stock', type_='foreignkey')
    op.create_foreign_key(None, 'add_stock', 'book', ['book_name'], ['book_name'], ondelete='CASCADE')
    op.drop_column('add_stock', 'isbn')
    # ### end Alembic commands ###
