"""empty message

Revision ID: e8868c8bc51e
Revises: 0e2774a3c0a9
Create Date: 2021-08-27 22:14:16.012097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8868c8bc51e'
down_revision = '0e2774a3c0a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('add_stock', sa.Column('isbn', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'add_stock', type_='foreignkey')
    op.create_foreign_key(None, 'add_stock', 'book', ['isbn'], ['isbn'], ondelete='CASCADE')
    op.drop_column('add_stock', 'book_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('add_stock', sa.Column('book_name', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'add_stock', type_='foreignkey')
    op.create_foreign_key(None, 'add_stock', 'book', ['book_name'], ['book_name'], ondelete='CASCADE')
    op.drop_column('add_stock', 'isbn')
    # ### end Alembic commands ###
