"""empty message

Revision ID: eef70a7f4f6a
Revises: cbcfebb23495
Create Date: 2021-08-26 18:08:29.141736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eef70a7f4f6a'
down_revision = 'cbcfebb23495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('add_stock', sa.Column('book_name', sa.String(), nullable=False))
    op.drop_constraint(None, 'add_stock', type_='foreignkey')
    op.create_foreign_key(None, 'add_stock', 'book', ['book_name'], ['book_name'], ondelete='CASCADE')
    op.drop_column('add_stock', 'book_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('add_stock', sa.Column('book_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'add_stock', type_='foreignkey')
    op.create_foreign_key(None, 'add_stock', 'book', ['book_id'], ['book_id'], ondelete='CASCADE')
    op.drop_column('add_stock', 'book_name')
    # ### end Alembic commands ###
